### ISSUE TITLE
Dataset Not found !!

### ISSUE THREAD

**Issue by pawan-bobbili** [Harathi123/Telugu-Character-Recognition-using-CNN#3]
[(http://lipitk.sourceforge.net/datasets/teluguchardata.htm)](url)
404 Error on this website.
Please provide an alternative source for dataset .

**Comment by jinglin-liang** [comment]
I meet the same problem. Have you found the alternative download link for the dataset? @pawan-bobbili @Harathi123

**Comment by BHARATH-BOLLAM** [comment]
Please contact me through my mail id bharathbollam36@gmail.com

**Comment by BHARATH-BOLLAM** [comment]
Dataset is available only for paid version.

**Comment by Harathi123** [comment]
please reach out to me over email if anyone need dataset
